Repository FESI-4-4/slid-todo, pull requests merged in 2024-10, with the labels that each got.

#13 [ CI/CD ] 배포용 레포지토리와 연결 작업
  .github/workflows/dispatch.yml
  .github/workflows/sync-develop.yml
  .github/workflows/sync-main.yml
Labels: :adhesive_bandage: chore

#18 [ 공통컴포넌트 ] 공통 컴포넌트 input 구현
  .prettierrc
  components/common/InputSlid.tsx
  package-lock.json
  package.json
  public/icons/IconArrowDown.tsx
  public/icons/IconVisibilityOff.tsx
  public/icons/IconVisibilityOn.tsx
Labels: :sparkles: feat

#21 [ 공통컴포넌트 ] 드롭다운 리스트 구현
  components/common/DropdownMenu.tsx
  package-lock.json
  public/icons/IconKebab.tsx
  public/icons/IconKebabWithCircle.tsx
Labels: :sparkles: feat, :art: style

#19 [ 노트 생성 ] 페이지 퍼블리싱
  app/createNote/page.tsx
  app/layout.tsx
  public/icons/IconAddLink.tsx
  public/icons/IconCheck.tsx
  public/icons/IconClose.tsx
  public/icons/IconEmbed.tsx
  public/icons/IconFlag.tsx
  public/icons/IconTextAlignLeft.tsx
  public/icons/IconTextAlignMiddle.tsx
  public/icons/IconTextAlignRight.tsx
  public/icons/IconTextBold.tsx
  public/icons/IconTextBulletPoint.tsx
  public/icons/IconTextColor.tsx
  public/icons/IconTextItalics.tsx
  public/icons/IconTextNumberPoint.tsx
  public/icons/IconTextUnderline.tsx
Labels: :art: style

#24 [ 로그인 & 회원가입 ] 로그인 & 회원가입 페이지 디자인 완료
  app/globals.css
  app/login/page.tsx
  app/signup/page.tsx
  components/AuthContainer.tsx
  components/LoginForm.tsx
  components/SignUpForm.tsx
  components/common/InputSlid.tsx
  public/Images/MainLogo.tsx
  tailwind.config.ts
Labels: :sparkles: feat, :art: style

#20 [ 공통컴포넌트 ] 모달
  app/page.tsx
  components/common/Modal.tsx
  public/icons/IconModalClose.tsx
Labels: :sparkles: feat

#28 [ 공통컴포넌트 ] 모달 수정
  components/common/Modal.tsx
Labels: :sparkles: feat, :art: style

#29 [ NAV ] 기본 디자인 구현
  app/layout.tsx
  components/Nav/NavBar.tsx
  components/Nav/NavDashBoard.tsx
  components/Nav/NavGoal.tsx
  components/Nav/NavProfile.tsx
  public/icons/IconDashboardSmall.tsx
  public/icons/IconExpand.tsx
  public/icons/IconFlagSmall.tsx
  public/icons/IconFold.tsx
  public/icons/IconPlusSmall.tsx
  public/images/ImageLogoWithText.tsx
  public/images/ImageProfile.tsx
  public/images/ImageProfileSmall.tsx
Labels: :art: style

#32 [ 노트 생성 ] 임시저장기능
  app/createNote/page.tsx
  app/layout.tsx
  app/todos/[todoId]/note/create/_view/NoteForm.tsx
  app/todos/[todoId]/note/create/page.tsx
Labels: :sparkles: feat

#35 [ 로그인 & 회원가입 ] api 작업 + 유효성검사
  app/api/auth/login/route.ts
  app/api/auth/refresh/route.ts
  components/LoginForm.tsx
  components/SignUpForm.tsx
  components/common/InputSlid.tsx
  constants/api.ts
  lib/api/interceptor.ts
  lib/api/login.ts
  lib/api/signUp.ts
  lib/schemas/authSchemas.ts
  package-lock.json
  package.json
  tailwind.config.ts
Labels: :sparkles: feat

#38 미들웨어
  middleware.ts
Labels: :sparkles: feat

#42 [ SVG 컴포넌트 ] HTML 형식 -> JSX 형식으로 변경
  public/icons/IconAddLink.tsx
  public/icons/IconArrowDown.tsx
  public/icons/IconCheck.tsx
  public/icons/IconDashboardSmall.tsx
  public/icons/IconEmbed.tsx
  public/icons/IconExpand.tsx
  public/icons/IconFold.tsx
  public/icons/IconKebab.tsx
  public/icons/IconKebabWithCircle.tsx
  public/icons/IconModalClose.tsx
  public/icons/IconPlusSmall.tsx
  public/icons/IconVisibilityOff.tsx
  public/icons/IconVisibilityOn.tsx
  public/images/ImageLogoWithText.tsx
  public/images/ImageProfile.tsx
  public/images/ImageProfileSmall.tsx
Labels: :bug: bug, :adhesive_bandage: chore

#43 [ 공통 컴포넌트 ] todo 요소탭 스타일링
  components/common/TodoItem/GoalTitle.tsx
  components/common/TodoItem/TodoIcon.tsx
  components/common/TodoItem/index.tsx
  public/icons/IconFile.tsx
  public/icons/IconGoal.tsx
  public/icons/IconInactive.tsx
  public/icons/IconLink.tsx
  public/icons/IconNoteView.tsx
  public/icons/IconNoteWrite.tsx
  public/icons/IconStateActive.tsx
Labels: :sparkles: feat, :art: style

#46 [ 대시보드 ] 대시보드 기본 디자인 구현
  app/(nav)/dashboard/page.tsx
  app/(nav)/layout.tsx
  app/layout.tsx
  components/Nav/NavBar.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/Progress.tsx
  components/dashboard/RecentTodo.tsx
  public/Images/ImageProgess.tsx
  public/Images/ImageProgessMobile.tsx
  public/Images/ImageProgessTablet.tsx
  public/icons/IconArrowRight.tsx
  public/icons/IconDashboardFlag.tsx
  public/icons/IconProgress.tsx
  public/icons/IconTodoRecently.tsx
  public/icons/IconUnchecked.tsx
Labels: :art: style

#47 [ 공통컴포넌트 ] 드롭다운 메뉴 아이콘 크기 오류 수정
  components/common/DropdownMenu.tsx
  components/common/TodoItem/TodoIcon.tsx
Labels: :bug: bug, :sparkles: feat

#50 [ 모든 할 일 페이지 ] 페이지 전체 스타일
  app/(nav)/todos/page.tsx
  components/AllTodos/AllTodoList.tsx
  components/AllTodos/Filters.tsx
  components/AllTodos/HeaderAllTodos.tsx
  lib/api/getTodos.ts
Labels: :sparkles: feat, :art: style

#51 [ 노트 생성 ] 조회/생성/수정 기능 개발
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  app/_view/QueryClientProvider.tsx
  app/layout.tsx
  lib/api/baseFetch.ts
  lib/hooks/useNoteMutation.ts
  lib/hooks/useTodosQuery.ts
  lib/types/index.d.ts
  middleware.ts
Labels: :sparkles: feat

#54 [ 공통컴포넌트 ] TodoIcon의 DropdownMenu에 className이 적용되지 않는 오류 수정
  components/common/TodoItem/TodoIcon.tsx
Labels: :bug: bug

#56 [ NAV ] NAV 관련 오류 수정
  app/(nav)/layout.tsx
  components/Nav/NavBar.tsx
Labels: :bug: bug

#55 [ 미들웨어 ] 엑세스 토큰 유효기간 지나면 토큰 재발급
  app/api/auth/login/route.ts
  app/api/auth/refresh/route.ts
  lib/api/getTodos.ts
  lib/api/interceptor.ts
  lib/api/login.ts
  lib/api/refreshToken.ts
  lib/utils/setAuthCookies.ts
  middleware.ts
Labels: :sparkles: feat

#59 [ 로그인 & 네브 ] 로그인 정보 NAV에 연결
  app/api/auth/logout/route.ts
  components/LoginForm.tsx
  components/Nav/NavBar.tsx
  components/Nav/NavProfile.tsx
  lib/api/login.ts
  lib/utils/auth.ts
Labels: :sparkles: feat

#64 [ 공통컴포넌트 ] 할일불러오기 쿼리 수정
  lib/hooks/useTodosQuery.ts
Labels: :wrench: refactor

#62 [ 모든 할 일 페이지 ] 타입오류 고치기 및 네브 레이아웃 css 변경
  app/(nav)/layout.tsx
  app/(nav)/todos/page.tsx
  components/AllTodos/HeaderAllTodos.tsx
  components/common/TodoItem/index.tsx
Labels: :bug: bug, :art: style

#66 [노트 모아보기 페이지] 페이지 스타일링
  app/(nav)/notes/[goalId]/page.tsx
  app/(nav)/todos/page.tsx
  components/AllTodos/HeaderAllTodos.tsx
  components/common/ButtonSlid.tsx
  components/common/PageLayout/PageContainer.tsx
  components/common/PageLayout/PageHeader.tsx
  components/notes/NoteGoalTitle.tsx
  components/notes/NoteItem.tsx
  components/notes/NotesList.tsx
  public/icons/IconRectangle.tsx
Labels: :sparkles: feat, :art: style

#69 [ Hotfix ] 깃허브 레포지토리 Imaegs 와 images 폴더 정리
  public/images/ImageProgess.tsx
  public/images/ImageProgessMobile.tsx
  public/images/ImageProgessTablet.tsx
  public/images/MainLogo.tsx
Labels: :bug: bug

#71 [ 모든 할 일 페이지 ] react-query 적용 및 todoitem 컴포넌트
  app/(nav)/todos/page.tsx
  app/layout.tsx
  components/AllTodos/AllTodoList.tsx
  components/common/TodoItem/TodoIcon.tsx
  components/common/TodoItem/index.tsx
  lib/hooks/useIntersectionObserver.ts
  lib/hooks/useTodosInfiniteQuery.ts
  lib/hooks/useUpdateTodoMutation.ts
  lib/utils/findMatchingTodoQueries.ts
  package-lock.json
  package.json
Labels: :sparkles: feat, :art: style

#74 [ 모든 할일 보기 ] 삭제기능
  components/common/PageLayout/PageContainer.tsx
  components/common/TodoItem/CheckIcon.tsx
  components/common/TodoItem/TodoIcon.tsx
  components/common/TodoItem/index.tsx
  lib/hooks/useDeleteTodoMutation.ts
Labels: :sparkles: feat

#76 [ 대시보드 ] 대시보드 기능 구현
  app/(nav)/dashboard/page.tsx
  components/AuthContainer.tsx
  components/Nav/NavBar.tsx
  components/Nav/NavProfile.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/GoalTodoCard.tsx
  components/dashboard/Progress.tsx
  components/dashboard/RecentTodo.tsx
  lib/hooks/useGoalsQuery.ts
  lib/hooks/useInfiniteGoalsQuery.ts
  lib/types/index.d.ts
  package-lock.json
  package.json
  public/Images/ImageProgress.tsx
  public/Images/ImageProgressMobile.tsx
  public/Images/ImageProgressTablet.tsx
  public/icons/IconArrowDown2.tsx
Labels: :bug: bug, :sparkles: feat, :art: style

#78 [ Hotfix ] 깃허브 레포지토리 Imaegs 와 images 폴더 정리 2
  public/images/ImageProgess.tsx
  public/images/ImageProgessMobile.tsx
  public/images/ImageProgessTablet.tsx
  public/images/ImageProgress.tsx
  public/images/ImageProgressMobile.tsx
  public/images/ImageProgressTablet.tsx
Labels: :bug: bug

#79 [노트 모아보기 페이지] 기능 구현
  app/(nav)/notes/[goalId]/page.tsx
  components/notes/NoteGoalTitle.tsx
  components/notes/NoteItem.tsx
  components/notes/NotesList.tsx
  lib/hooks/useDeleteNoteMutation.ts
  lib/hooks/useNotesInfiniteQuery.ts
Labels: :sparkles: feat, :art: style

#82 [ Build ] 빌드를 위한 애러 잡기
  app/(nav)/todos/page.tsx
  components/AllTodos/TodoContent.tsx
  package-lock.json
Labels: :bug: bug

#84 [ 공통컴포넌트 ] Progressbar 제작
  components/common/ProgressBar.tsx
  components/dashboard/GoalTodoCard.tsx
  lib/hooks/useTodoProgressQuery.ts
Labels: :sparkles: feat, :art: style

#87 [ 공통컴포넌트 ] 모달 ref 추가
  components/common/Modal.tsx
Labels: :sparkles: feat

#91 [ React-Query ] 버그 고친이후 잔처리
  app/_view/QueryClientProvider.tsx
  components/AllTodos/AllTodoList.tsx
  components/AllTodos/TodoContent.tsx
  components/common/TodoItem/CheckIcon.tsx
  components/common/TodoItem/GoalTitle.tsx
  components/common/TodoItem/TodoIcon.tsx
  components/common/TodoItem/index.tsx
  lib/api/getTodos.ts
  lib/hooks/useTodosInfiniteQuery.ts
  lib/hooks/useUpdateTodoMutation.ts
  lib/types/todos.ts
  lib/utils/findMatchingTodoQueries.ts
Labels: :bug: bug, :adhesive_bandage: chore

#89 [ 노트 ] 텍스트 에디터
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/(nav)/todos/[todoId]/_view/TiptapCharacterCount.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  components/TiptapEditor.tsx
  components/TiptapEditorProvider.tsx
  package-lock.json
  package.json
  public/icons/IconTextColor.tsx
  public/icons/IconTextHighlight.tsx
Labels: :sparkles: feat

#94 [ 노트 ] 링크임베드
  app/(nav)/todos/[todoId]/_view/LinkEmbed.tsx
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  components/TiptapEditorProvider.tsx
Labels: :sparkles: feat

#95 [ 노트 ] 반응형 디자인 개발
  app/(nav)/todos/[todoId]/_view/LinkEmbed.tsx
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  app/globals.css
  components/TiptapEditor.tsx
  components/common/Modal.tsx
Labels: :art: style

#98 [할 일 생성 & 수정] 할 일 생성 수정 모달 스타일링하기 및 폼 상태관리
  components/Nav/NavBar.tsx
  components/common/InputSlid.tsx
  components/common/TodoItem/TodoIcon.tsx
  components/common/TodoItem/index.tsx
  components/modal/todoModal/ButtonUploadFile.tsx
  components/modal/todoModal/CheckboxToggle.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
  lib/hooks/useAddTodoMutation.ts
  lib/schemas/todosSchemas.ts
  public/icons/IconStateActiveWhite.tsx
Labels: :sparkles: feat, :art: style

#104 [ 공통컴포넌트 ] 모달 수정
  components/common/Modal.tsx
Labels: :sparkles: feat

#105 [ 할 일 생성 모달 및 회원가입] 요구사항명세서에 맞게 추가 및 수정
  app/(nav)/notes/[goalId]/page.tsx
  app/(nav)/todos/page.tsx
  components/AllTodos/AllTodoList.tsx
  components/AllTodos/TodoContent.tsx
  components/SignUpForm.tsx
  components/common/InputSlid.tsx
  components/common/TodoItem/GoalTitle.tsx
  components/common/TodoItem/index.tsx
  components/dashboard/GoalTodoCard.tsx
  components/dashboard/RecentTodo.tsx
  lib/api/getTodos.ts
  lib/api/login.ts
  lib/api/signUp.ts
  lib/schemas/todosSchemas.ts
  lib/types/auth.ts
Labels: :sparkles: feat, :art: style, :adhesive_bandage: chore

#107 [ 레이아웃 ] 메타데이터 작성 및 파비콘 변경
  app/(nav)/dashboard/layout.tsx
  app/(nav)/notes/[goalId]/layout.tsx
  app/(nav)/todos/[todoId]/create/layout.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/layout.tsx
  app/(nav)/todos/layout.tsx
  app/favicon.ico
  app/icon.svg
  app/layout.tsx
  app/login/layout.tsx
  app/signup/layout.tsx
Labels: :sparkles: feat

#96 [ 목표 상세 페이지 / 대시보드 ] 기능 및 디자인 제작
  app/(nav)/goals/[goalId]/page.tsx
  components/Nav/NavGoal.tsx
  components/common/DropdownMenu.tsx
  components/common/GoalTitleWithProgress.tsx
  components/common/ProgressBar.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/GoalTodoCard.tsx
  components/dashboard/TodoItemsDashboard.tsx
  components/goals/TodoItemsGoal.tsx
  lib/hooks/useGoalQuery.ts
  lib/hooks/useGoalsQuery.ts
  public/icons/IconFlag.tsx
  public/icons/IconNoteAll.tsx
Labels: :sparkles: feat, :art: style

#109 배포 타입오류 수정
  app/(nav)/todos/[todoId]/_view/LinkEmbed.tsx
  app/(nav)/todos/[todoId]/_view/ModalSavedNote.tsx
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormContent.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  components/common/Modal.tsx
  next.config.mjs
Labels: :bug: bug

#112 [ 할 일 생성 & 수정 모달 ] 보완
  components/modal/todoModal/ButtonUploadFile.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
  lib/schemas/todosSchemas.ts
  lib/utils/cleanedFormData.ts
Labels: :bug: bug

#113 [ 공통컴포넌트 ] dropdownmenu 아이콘 클릭시 메뉴 닫힘 기능 추가
  app/(nav)/layout.tsx
  components/common/DropdownMenu.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/TodoItemsDashboard.tsx
  components/goals/TodoItemsGoal.tsx
Labels: :bug: bug

#115 [ hotfix ] 폴더 이름 변경
  components/allTodos/AllTodoList.tsx
  components/allTodos/Filters.tsx
  components/allTodos/TodoContent.tsx
  components/common/pageLayout/PageContainer.tsx
  components/common/pageLayout/PageHeader.tsx
  components/common/todoItem/CheckIcon.tsx
  components/common/todoItem/GoalTitle.tsx
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/index.tsx
  components/nav/NavBar.tsx
  components/nav/NavDashBoard.tsx
  components/nav/NavGoal.tsx
  components/nav/NavProfile.tsx
Labels: :bug: bug

#119 모달 닫기 전 콜백함수 추가
  components/common/Modal.tsx
  components/nav/NavProfile.tsx
Labels: :sparkles: feat

#120 ✨ #118 feat: 프로그래스바 즉시반영 되게 invalidate 추가
  lib/hooks/useAddTodoMutation.ts
  lib/hooks/useDeleteTodoMutation.ts
  lib/hooks/useUpdateTodoMutation.ts
Labels: :sparkles: feat

#122 [ layout ] 폰트 작업 및 og에 사용할 이미지 등록
  app/globals.css
  public/images/ImageOG.png
Labels: :adhesive_bandage: chore

#124 [ 노트 모아보기 / 모든 할 일 ] 노트 사이드시트 개발
  app/(nav)/todos/[todoId]/note/[noteId]/layout.tsx
  components/TiptapEditorProvider.tsx
  components/common/Sheet.tsx
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/index.tsx
  components/notes/NoteDetail.tsx
  components/notes/NoteItem.tsx
  lib/hooks/useNoteQuery.ts
  lib/types/index.d.ts
Labels: :art: style

#126 [ 할 일 ] 할 일 생성/수정 목표 선택 DropdownMenu로 변경
  components/common/DropdownMenu.tsx
  components/modal/todoModal/GoalSelector.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
Labels: :sparkles: feat, :art: style

#130 [ Fix ]🐛 대시보드 useTodosInfiniteQuery로 변경
  components/dashboard/RecentTodo.tsx
  components/dashboard/TodoItemsDashboard.tsx
Labels: :bug: bug

#129 [ 노트 ] 노트 생성수정 페이지 할일, 목표명 상태 참조 변경
  app/(nav)/todos/[todoId]/_view/NoteFormContent.tsx
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/index.tsx
  components/notes/NoteDetail.tsx
  components/notes/NoteItem.tsx
Labels: :wrench: refactor

#135 [ 랜딩 페이지 ] 기본 레이아웃 구조 잡기
  app/(nav)/layout.tsx
  app/layout.tsx
  app/page.tsx
  components/common/pageLayout/PageContainer.tsx
  components/landingPage/SectionContainer.tsx
  middleware.ts
Labels: :sparkles: feat, :art: style

#136 [ 노트 ] 임시저장글 불러오기 오류 수정
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormContent.tsx
Labels: :bug: bug

#139 [ 할일 ] 할일명 클릭으로 노트 시트 뜨는 기능 삭제 / 노트 수정 아이콘 라우팅 수정
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/index.tsx
Labels: :sparkles: feat

#140 [ 모달 ] 회원가입 축하 모달 및 기타 작업
  components/SignUpForm.tsx
  components/dashboard/GoalTodoCard.tsx
  components/modal/SignupSuccessModal.tsx
  components/modal/todoModal/TodoAddModal.tsx
Labels: :sparkles: feat, :art: style

#141 [ 노트 ] 노트 수정/생성 후 리디렉션 추가
  app/(nav)/todos/[todoId]/_view/NoteFormContent.tsx
  app/actions.ts
Labels: :bug: bug

#132 [ 공통컴포넌트 ] ModalProvider 프롭스 추가
  components/common/Modal.tsx
Labels: :wrench: refactor

#146 [ 대시보드 ] 전체 달성률 표시
  components/dashboard/Progress.tsx
  components/dashboard/ProgressText.tsx
  lib/hooks/useTodoProgressQuery.ts
  lib/types/todos.ts
Labels: :sparkles: feat

#151 [ 노트 ] 임시저장 몇초전 컴포넌트 개발
  app/(nav)/todos/[todoId]/_view/NoteFormContent.tsx
  app/(nav)/todos/[todoId]/_view/SecondsTimer.tsx
Labels: :sparkles: feat

#150 [ 노트 ] 노트 생성페이지 목표없는 할일일때 undefined 표시 수정
  components/common/todoItem/TodoIcon.tsx
Labels: :bug: bug
