Repository FESI-4-4/slid-todo, pull requests merged in 2024-11, with the labels that each got.

#156 [ 타입 정리 ] todo, auth
  components/allTodos/AllTodoList.tsx
  components/common/Modal.tsx
  components/common/todoItem/GoalTitle.tsx
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/index.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/GoalTodoCard.tsx
  components/dashboard/TodoItemsDashboard.tsx
  components/goals/TodoItemsGoal.tsx
  components/modal/todoModal/GoalSelector.tsx
  components/modal/todoModal/TodoEditModal.tsx
  components/nav/NavGoal.tsx
  lib/hooks/useGoalQuery.ts
  lib/hooks/useInfiniteGoalsQuery.ts
  lib/hooks/useNoteQuery.ts
  lib/hooks/useTodoProgressQuery.ts
  lib/hooks/useTodosInfiniteQuery.ts
  lib/hooks/useTodosQuery.ts
  lib/hooks/useUpdateTodoMutation.ts
  lib/types/todo.ts
  lib/types/todos.ts
  lib/utils/findMatchingTodoQueries.ts
Labels: :adhesive_bandage: chore

#163 [ 공통컴포넌트 ] 모달 오버레이 클래스 수정할 수 있도록 twMerge 추가
  components/common/Modal.tsx
Labels: :art: style

#162 [ 노트 ] 생성/삭제 후 할일 노트아이콘 업데이트
  app/(nav)/todos/[todoId]/_view/NoteFormContent.tsx
  components/common/todoItem/TodoIcon.tsx
  components/notes/NoteDetail.tsx
  lib/api/baseFetch.ts
Labels: :bug: bug

#167 [ 공통컴포넌트 ] 시트 위치 선택할 수 있도록 프롭스 추가
  components/common/Sheet.tsx
  components/common/todoItem/TodoIcon.tsx
Labels: :art: style

#168 [ TodoItem ] 변경사항 반영
  app/api/auth/login/route.ts
  components/common/todoItem/GoalTitle.tsx
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/TodoTitle.tsx
  components/common/todoItem/index.tsx
  constants/index.ts
  lib/api/signUp.ts
  middleware.ts
  public/icons/IconFile.tsx
  public/icons/IconGoal.tsx
  public/icons/IconLink.tsx
  public/icons/IconNoteView.tsx
  public/icons/IconNoteWrite.tsx
Labels: :sparkles: feat, :art: style

#171 [ Drawer ] 모바일 용 Drawer 스타일링
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/TodoTitle.tsx
  components/drawer/TodoContentsDrawer.tsx
Labels: :sparkles: feat, :art: style

#170 [ 노트 ] UI 수정
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormContent.tsx
Labels: :bug: bug, :art: style

#174 [ 할 일 생성 & 수정 ] 관련 모달 ref에서 상태값 제어로 변경
  components/allTodos/TodoContent.tsx
  components/common/todoItem/TodoIcon.tsx
  components/dashboard/GoalTodoCard.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
  components/nav/NavBar.tsx
  components/notes/NoteItem.tsx
  components/sheet/NoteViewSheet.tsx
Labels: :wrench: refactor

#176 [ Drawer ] 모바일 용 Drawer 기능 개발
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/TodoTitle.tsx
  components/drawer/TodoContentsDrawer.tsx
  components/drawer/TodoContentsDrawer/ActionButtons.tsx
  components/drawer/TodoContentsDrawer/TodoContentsDrawer.tsx
Labels: :sparkles: feat

#179 [ 모달 ] 각종 확인모달
  components/SignUpForm.tsx
  components/common/todoItem/TodoIcon.tsx
  components/modal/DeleteConfirmationModal.tsx
  components/modal/SignupSuccessModal.tsx
  components/notes/NoteDetail.tsx
  components/notes/NoteItem.tsx
  constants/index.ts
Labels: :wrench: refactor, :sparkles: feat

#182 [ NAV ] 네비게이션바 접는 기능 구현
  app/(nav)/dashboard/page.tsx
  app/(nav)/goals/[goalId]/layout.tsx
  app/(nav)/goals/[goalId]/page.tsx
  app/(nav)/layout.tsx
  components/dashboard/GoalTodo.tsx
  components/nav/NavAllTodos.tsx
  components/nav/NavBar.tsx
  components/nav/NavDashBoard.tsx
  components/nav/NavGoal.tsx
  constants/index.ts
  public/icons/IconFold.tsx
  public/icons/IconHamburger.tsx
  public/images/ImageLogo.tsx
Labels: :sparkles: feat, :art: style

#183 [ 노트 ] 노트 삭제 후 query invalidation 예외 처리 및 삭제
  components/notes/NoteDetail.tsx
  lib/hooks/useDeleteNoteMutation.ts
Labels: :bug: bug

#184 [ 목표 상세 ] 디자인 오류 수정
  app/(nav)/dashboard/page.tsx
  app/(nav)/goals/[goalId]/page.tsx
  components/common/GoalTitleWithProgress.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/Progress.tsx
  components/dashboard/RecentTodo.tsx
  components/goals/TodoItemsGoal.tsx
Labels: :art: style

#185 [ 노트 모아보기 페이지 + 모든 목표 페이지 ] 데이터 패칭 개선
  app/(nav)/notes/[goalId]/page.tsx
  app/(nav)/todos/page.tsx
  components/allTodos/AllTodoList.tsx
  components/allTodos/TodoContent.tsx
  components/allTodos/TodosContent.tsx
  components/allTodos/TodosContext.tsx
  components/allTodos/TodosHeader.tsx
  components/notes/NoteGoalTitle.tsx
  components/notes/NoteItem.tsx
  components/notes/NotesContent.tsx
  components/notes/NotesList.tsx
Labels: :wrench: refactor, :sparkles: feat

#192 [ 공통컴포넌트 ] 모바일 외 사이즈 타이틀 클릭 #190
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/TodoTitle.tsx
  components/drawer/TodoContentsDrawer/TodoContentsDrawer.tsx
  components/modal/ConfirmationModal.tsx
  components/modal/DeleteConfirmationModal.tsx
  components/notes/NoteDetail.tsx
  components/notes/NoteItem.tsx
  constants/index.ts
Labels: :wrench: refactor, :sparkles: feat

#194 [ 미들웨어 ] matcher에 하위 URL도 적용되게 수정
  middleware.ts
Labels: :bug: bug

#197 [ 할일 ]: TodosHeader 및 TodoItemsGoal에서 모달 열기 기능 추가
  components/allTodos/TodosHeader.tsx
  components/goals/TodoItemsGoal.tsx
Labels: :adhesive_bandage: chore

#198 [ 목표 ] 목표 수정/삭제 기능 추가
  components/common/GoalTitleWithProgress.tsx
  constants/index.ts
  lib/hooks/useDeleteGoalMutation.ts
  lib/hooks/useInfiniteGoalsQuery.ts
  lib/hooks/useUpdateGoalMutation.ts
Labels: :sparkles: feat

#200 [ 모달 관련 수정 ] 모달 CSS 수정 및 기타작업
  components/common/Modal.tsx
  components/drawer/TodoContentsDrawer/TodoContentsDrawer.tsx
  components/modal/todoModal/ButtonUploadFile.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
  tailwind.config.ts
Labels: :bug: bug, :sparkles: feat, :art: style

#202 [ 대시보드 ] 할 일 / 목표 없을 시 화면에 메세지 출력
  app/(nav)/dashboard/page.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/RecentTodo.tsx
Labels: :adhesive_bandage: chore

#204 [ 대시보드 ] 할 일 모두 로드시 더보기 제거
  components/dashboard/TodoItemsDashboard.tsx
Labels: :sparkles: feat

#210 [ 로그인 & 회원가입 ] 서버관련 에러처리
  components/LoginForm.tsx
  components/SignUpForm.tsx
  constants/index.ts
  lib/api/signUp.ts
  lib/hooks/useEmailValidation.ts
  lib/types/auth.ts
  lib/utils/parseError.ts
  middleware.ts
Labels: :file_folder: docs, :wrench: refactor, :sparkles: feat, :art: style

#212 [ NAV ] 모바일, 태블릿에서 페이지 이동시에만 NAV가 접히도록 변경
  components/nav/NavBar.tsx
Labels: :sparkles: feat

#214 [ 노트 모아보기 & 아이콘 ] 스타일링 추가
  components/common/todoItem/TodoIcon.tsx
  components/drawer/TodoContentsDrawer/ActionButtons.tsx
  components/drawer/TodoContentsDrawer/TodoContentsDrawer.tsx
  components/notes/NoteItem.tsx
  public/icons/IconEditTodo.tsx
  public/icons/IconFile.tsx
  public/icons/IconKebabWithCircle.tsx
  public/icons/IconLink.tsx
  public/icons/IconNoteView.tsx
  public/icons/IconNoteWrite.tsx
  public/icons/IconTrash.tsx
Labels: :bug: bug, :art: style

#217 [ 대시보드 ] 원형 프로그레스바 및 애니메이션 추가
  components/dashboard/CircleProgressBar.tsx
  components/dashboard/Progress.tsx
  components/dashboard/ProgressText.tsx
Labels: :sparkles: feat, :art: style

#219 [ 404 페이지 ] 만들기
  app/not-found.tsx
  components/notes/NotesContent.tsx
  lib/hooks/useNotesInfiniteQuery.ts
  lib/types/todo.ts
  public/images/MainLogo.tsx
Labels: :bug: bug, :sparkles: feat, :art: style

#221 [ 노트 ] 렌더링 최적화 외
  app/(nav)/todos/[todoId]/_view/AddLinkModal.tsx
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormContent.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormEditorButtons.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormLinkModal.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormSection.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormSections.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormTitleInput.tsx
  app/(nav)/todos/[todoId]/_view/OpenSavedNoteModal.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  components/TiptapEditor.tsx
  components/TiptapEditorProvider.tsx
  components/common/Modal.tsx
  components/notes/NoteDetail.tsx
  lib/types/todo.ts
Labels: :bug: bug, :wrench: refactor, :art: style

#224 빌드 에러 수정 외
  components/notes/NoteDetail.tsx
  components/notes/NoteItem.tsx
Labels: :bug: bug, :art: style

#227 [ 노트 ]노트 링크 삭제 기능 추가 외
  app/(nav)/todos/[todoId]/_view/NoteFormSection.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
Labels: :sparkles: feat, :art: style

#229 [ Note 타입 수정 ]
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  lib/hooks/useNoteQuery.ts
  lib/types/todo.ts
Labels: :bug: bug, :adhesive_bandage: chore

#231 [ 에러 관련 ] 에러 처리 중앙화
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  app/error.tsx
  components/LoginForm.tsx
  components/SignUpForm.tsx
  components/common/todoItem/TodoTitle.tsx
  components/notes/NotesContent.tsx
  constants/index.ts
  lib/api/baseFetch.ts
  lib/api/errorHandlers.ts
  lib/api/login.ts
  lib/api/signUp.ts
  lib/hooks/useEmailValidation.ts
  lib/utils/getDefaultErrorMessage.ts
Labels: :wrench: refactor, :sparkles: feat

#234 [ not-found 리다이렉션 방법 변경 ]
  app/(nav)/goals/[goalId]/page.tsx
  app/(nav)/notes/[goalId]/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  app/error.tsx
  app/not-found.tsx
  components/common/GoalTitleWithProgress.tsx
  components/notes/NotesContent.tsx
  constants/index.ts
  lib/api/errorHandlers.ts
  lib/hooks/useGoalQuery.ts
Labels: :wrench: refactor, :adhesive_bandage: chore

#235 [ NAV ] 접고 펼때 애니메이션 추가
  app/(nav)/layout.tsx
  components/nav/NavBar.tsx
  components/nav/NavBarTablet.tsx
  components/nav/NavBarTemp.tsx
Labels: :art: style

#237 [ 대시보드 ] 반응형 디자인 개선
  app/(nav)/dashboard/page.tsx
  components/dashboard/Progress.tsx
  components/dashboard/TodoItemsDashboard.tsx
Labels: :art: style

#240 [ NAV ] 모바일에서 기본적으로 nav가 열려있던 오류 수정
  components/nav/NavBarTemp.tsx
Labels: :bug: bug

#243 [ 랜딩 페이지 ] 애니메이션 효과 추가
  app/page.tsx
  components/drawer/TodoContentsDrawer/TodoContentsDrawer.tsx
  components/landingPage/FirstSection.tsx
  components/landingPage/FourthSection.tsx
  components/landingPage/SecondSection.tsx
  components/landingPage/ThirdSection.tsx
  lib/animations/variants.ts
  package-lock.json
  package.json
Labels: :art: style

#244 [ 목표 ] 목표 관련 애니메이션 추가
  app/(nav)/goals/[goalId]/page.tsx
  components/common/ProgressBar.tsx
Labels: :art: style

#247 [ 목표 상세보기 페이지 ] 반응형 스타일링 개선
  components/goals/TodoItemsGoal.tsx
Labels: :art: style

#245 [ 공통컴포넌트 ] sheet 컴포넌트 애니메이션 적용
  components/common/Sheet.tsx
  components/drawer/TodoContentsDrawer/ActionButtons.tsx
Labels: :art: style

#249 [ NAV ] style 수정 및 tablet 닫기 버튼 제거
  components/nav/NavBarTablet.tsx
  components/nav/NavBarTemp.tsx
Labels: :art: style

#256 [ 할 일 생성 & 수정 ] 엔터키 & 모달 필수요소 표시
  components/common/Modal.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
Labels: :bug: bug, :art: style

#259 [ 공통 컴포넌트 ] 토스트 구현
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  app/layout.tsx
  components/common/toast/toastStore.ts
  components/common/toast/toaster.tsx
  components/common/toast/useToast.ts
  public/icons/IconError.tsx
  public/icons/IconSuccess.tsx
  tailwind.config.ts
Labels: :sparkles: feat

#262 [ 노트 ] 임베드 안 되는 링크 예외 처리
  app/(nav)/todos/[todoId]/_view/NoteFormSections.tsx
Labels: :sparkles: feat

#263 [ 토스트 ] 뮤테이션 관련 토스트 연결
  app/(nav)/todos/[todoId]/_view/NoteForm.tsx
  lib/hooks/useAddGoalMutation.ts
  lib/hooks/useAddTodoMutation.ts
  lib/hooks/useDeleteGoalMutation.ts
  lib/hooks/useDeleteNoteMutation.ts
  lib/hooks/useDeleteTodoMutation.ts
  lib/hooks/useUpdateGoalMutation.ts
  lib/hooks/useUpdateTodoMutation.ts
Labels: :sparkles: feat

#267 [ 노트 ] 노트 사이드시트 링크임베드 예외 처리 적용
  app/(nav)/todos/[todoId]/_view/NoteFormSections.tsx
  components/notes/NoteDetail.tsx
Labels: :sparkles: feat

#268 [ 로그인 ] 리다이렉션 방식 변경
  components/LoginForm.tsx
Labels: :wrench: refactor

#272 [ SVG 로고 ] 짤리는 부분 수정
  components/allTodos/TodosContent.tsx
  public/images/MainLogo.tsx
Labels: :art: style, :adhesive_bandage: chore

#276 [ NAV ] 리팩토링
  app/(nav)/layout.tsx
  components/nav/Nav.tsx
  components/nav/NavBar.tsx
  components/nav/NavBarTablet.tsx
  components/nav/NavBarTemp.tsx
  components/nav/NavContent.tsx
  components/nav/NavHeader.tsx
Labels: :wrench: refactor

#277 [ 랜딩 페이지 ] 이미지 넣기
  app/page.tsx
  components/landingPage/FirstSection.tsx
  components/landingPage/FourthSection.tsx
  components/landingPage/SecondSection.tsx
  components/landingPage/SectionContainer.tsx
  components/landingPage/ThirdSection.tsx
  public/images/ImageEmbed.png
  public/images/ImageGoalDoughnut.png
Labels: :art: style

#279 [ NAV ] 목표가 없을 경우 nav content 가로 길이가 짧은 오류 수정
  components/nav/NavContent.tsx
Labels: :bug: bug, :art: style

#280 [ 랜딩 페이지 ] footer 만들기
  app/page.tsx
  components/landingPage/FooterSection.tsx
Labels: :sparkles: feat, :art: style

#282 [ 노트 ] 임베드 애니메이션 외
  app/(nav)/todos/[todoId]/_view/NoteFormSection.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormSections.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  components/notes/NoteDetail.tsx
Labels: :art: style

#283 [ 목표 ] 목표 삭제시 목표가 3개밖에 안나오는 오류 수정
  lib/hooks/useInfiniteGoalsQuery.ts
  lib/hooks/useUpdateGoalMutation.ts
Labels: :bug: bug

#284 [ 로딩 페이지 ] 로딩 페이지 구현 #281
  app/(nav)/dashboard/page.tsx
  app/(nav)/todos/page.tsx
  app/loading.tsx
  components/allTodos/AllTodoList.tsx
  components/allTodos/TodosContent.tsx
  components/dashboard/Progress.tsx
  components/dashboard/RecentTodo.tsx
  tailwind.config.ts
Labels: :sparkles: feat, :adhesive_bandage: chore

#286 [ 랜딩 페이지 ] 푸터 스타일 변경
  components/landingPage/FooterSection.tsx
Labels: :art: style

#289 [ 모든 할 일 ] 웹 접근성 향상
  components/allTodos/AllTodoList.tsx
  components/allTodos/Filters.tsx
  components/allTodos/TodosContent.tsx
  components/common/pageLayout/PageContainer.tsx
  components/common/pageLayout/PageHeader.tsx
  components/common/todoItem/CheckIcon.tsx
  components/common/todoItem/GoalTitle.tsx
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/TodoTitle.tsx
  components/common/todoItem/index.tsx
  public/icons/IconLink.tsx
  public/icons/IconNoteView.tsx
  public/icons/IconNoteWrite.tsx
Labels: :wrench: refactor

#295 [ NAV ] 목표 호버시 케밥 아이콘으로 빠른 수정삭제 기능 추가
  app/(nav)/goals/[goalId]/page.tsx
  components/common/DropdownMenu.tsx
  components/common/todoItem/TodoIcon.tsx
  components/goals/GoalTitleWithProgress.tsx
  components/modal/ConfirmationModal.tsx
  components/nav/NavGoal.tsx
  components/notes/NoteDetail.tsx
  components/notes/NoteItem.tsx
Labels: :sparkles: feat

#293 [ 랜딩 페이지 ] 웹 접근성 향상
  app/page.tsx
  components/landingPage/FirstSection.tsx
  components/landingPage/FooterSection.tsx
  components/landingPage/FourthSection.tsx
  components/landingPage/SecondSection.tsx
  components/landingPage/SectionContainer.tsx
  components/landingPage/ThirdSection.tsx
Labels: :wrench: refactor

#296 [ 노트 ] 임베드링크 버그 수정
  app/(nav)/todos/[todoId]/_view/NoteFormSections.tsx
Labels: :bug: bug

#298 [ NAV ] 목표 호버시 케밥 아이콘으로 빠른 수정삭제 기능 (추가 커밋)
  components/modal/ConfirmationModal.tsx
  lib/hooks/useUpdateGoalMutation.ts
Labels: :adhesive_bandage: chore

#299 [ 노트 모아보기 페이지] 웹 접근성 향상
  components/common/todoItem/index.tsx
  components/notes/NoteGoalTitle.tsx
  components/notes/NoteItem.tsx
  components/notes/NotesContent.tsx
  components/notes/NotesList.tsx
Labels: :wrench: refactor

#301 [ 공통 컴포넌트 ] 토스트, not-found, error, loading 웹 접근성 향상
  app/error.tsx
  app/loading.tsx
  app/not-found.tsx
  components/common/toast/toaster.tsx
Labels: :wrench: refactor

#305 [ 할 일 생성 & 수정 ] 이미지 파일 분류, 이미지 파일 미리보기
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
  constants/index.ts
  lib/utils/isValidImageUrl.ts
  next.config.mjs
Labels: :sparkles: feat

#307 [ 대시보드 ] 웹 접근성 향상
  components/dashboard/GoalTodo.tsx
  components/dashboard/GoalTodoCard.tsx
  components/dashboard/Progress.tsx
  components/dashboard/ProgressText.tsx
  components/dashboard/RecentTodo.tsx
  components/dashboard/TodoItemsDashboard.tsx
  components/goals/TodoItemsGoal.tsx
Labels: :wrench: refactor

#308 [ 노트 ] aria 속성 추가 외
  app/(nav)/todos/[todoId]/_view/NoteFormEditorButtons.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormSection.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormTitleInput.tsx
  components/TiptapEditor.tsx
  components/common/DropdownMenu.tsx
  components/common/Modal.tsx
  components/common/Sheet.tsx
  components/notes/NoteDetail.tsx
  middleware.ts
Labels: :bug: bug, :sparkles: feat, :adhesive_bandage: chore

#310 [ 노트 ]노트작성페이지 텍스트에디터 포커스 영역 확장
  components/TiptapEditor.tsx
Labels: :sparkles: feat

#311 [ 랜딩 페이지 ] 네비게이션 커서추가, 푸터 버튼추가
  app/page.tsx
  components/landingPage/FooterSection.tsx
  components/landingPage/ZeppelinAd.tsx
  tailwind.config.ts
Labels: :wrench: refactor, :sparkles: feat

#313 [할 일 생성 & 수정 ] 링크 유효성 검사 수정
  components/common/todoItem/TodoIcon.tsx
  components/drawer/TodoContentsDrawer/ActionButtons.tsx
  lib/schemas/todosSchemas.ts
  lib/utils/openExternalSite.ts
Labels: :wrench: refactor, :sparkles: feat

#315 [ 공통컴포넌트 ] 드롭다운 메뉴, 프로그레스바 접근성 향상
  components/common/DropdownMenu.tsx
  components/common/ProgressBar.tsx
  components/common/todoItem/TodoIcon.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/GoalTodoCard.tsx
  components/dashboard/Progress.tsx
  components/dashboard/RecentTodo.tsx
  components/dashboard/TodoItemsDashboard.tsx
  components/goals/GoalTitleWithProgress.tsx
  components/modal/todoModal/GoalSelector.tsx
  components/notes/NoteDetail.tsx
  components/notes/NoteItem.tsx
Labels: :wrench: refactor

#319 [ 목표 상세 ] 목표 상세 페이지 접근성 개선
  app/(nav)/goals/[goalId]/page.tsx
  components/goals/GoalTitleWithProgress.tsx
  components/goals/TodoItemsGoal.tsx
Labels: :wrench: refactor

#321 [ NAV ] 새 목표 input에 내용이 있을 경우 새 목표 버튼 색상 변경
  components/nav/AddGoalButton.tsx
  components/nav/NavGoal.tsx
Labels: :wrench: refactor, :art: style

#322 [ todosSchemas] LinkUrl유효성검사 문제
  lib/schemas/todosSchemas.ts
Labels: :bug: bug

#324 [ 할 일 수정 ] 파일이 삭제 수정이 안되는 문제
  lib/utils/cleanedFormData.ts
Labels: :bug: bug

#325 [ 공통컴포넌트 ] 새 할일 DropdownMenu 스타일 오류 개선 및 웹 접근성 향상
  components/common/DropdownMenu.tsx
  components/modal/todoModal/GoalSelector.tsx
Labels: :bug: bug, :wrench: refactor, :art: style

#329 [ SVG 아이콘 ] 선 색
  components/common/todoItem/index.tsx
  public/icons/IconFile.tsx
  public/icons/IconLink.tsx
  public/icons/IconNoteView.tsx
  public/icons/IconNoteWrite.tsx
Labels: :art: style

#332 [ NAV ] 웹 접근성 개선 및 새 목표 기능 개선
  components/nav/AddGoalButton.tsx
  components/nav/Nav.tsx
  components/nav/NavAllTodos.tsx
  components/nav/NavContent.tsx
  components/nav/NavDashBoard.tsx
  components/nav/NavGoal.tsx
  components/nav/NavHeader.tsx
  public/images/ImageLogo.tsx
  public/images/ImageLogoWithText.tsx
  public/images/ImageProfile.tsx
  public/images/ImageProfileSmall.tsx
Labels: :wrench: refactor, :art: style

#333 [ Form 관련 ] 포커스 주기
  components/LoginForm.tsx
  components/SignUpForm.tsx
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/TodoImage.tsx
  components/common/todoItem/TodoTitle.tsx
  components/common/todoItem/index.tsx
  components/modal/todoModal/ButtonUploadFile.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
  lib/api/baseFetch.ts
Labels: :wrench: refactor, :sparkles: feat

#335 [ form 관련 ] 할일 추가 안됨
  app/fonts/GeistMonoVF.woff
  app/fonts/GeistVF.woff
  components/common/todoItem/TodoImage.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
  lib/utils/cleanedFormData.ts
Labels: :bug: bug

#337 [ 노트 모아보기 ] 초기값 SSR
  app/(nav)/notes/[goalId]/page.tsx
  components/common/todoItem/TodoImage.tsx
  components/notes/NotesContent.tsx
  lib/hooks/useNotesInfiniteQuery.ts
Labels: :wrench: refactor

#339 [ 모든 할 일 ] 초기값 SSR
  app/(nav)/todos/page.tsx
  components/allTodos/AllTodoList.tsx
  components/allTodos/TodosContent.tsx
  components/common/todoItem/TodoImage.tsx
  components/common/todoItem/index.tsx
  lib/hooks/useNotesInfiniteQuery.ts
  lib/hooks/useTodosInfiniteQuery.ts
Labels: :wrench: refactor

#341 [ 모든 할 일 ] 필터 작동 안됨
  app/(nav)/todos/page.tsx
  components/common/todoItem/TodoImage.tsx
  components/common/todoItem/index.tsx
Labels: :bug: bug

#345 [ 전체 레이아웃 ] CSS 구조변경
  app/(nav)/dashboard/page.tsx
  app/(nav)/layout.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  app/globals.css
  components/common/Modal.tsx
  components/common/Sheet.tsx
  components/common/pageLayout/PageContainer.tsx
  components/common/todoItem/index.tsx
  components/dashboard/Progress.tsx
  components/dashboard/RecentTodo.tsx
  components/nav/Nav.tsx
  components/nav/NavGoal.tsx
  components/nav/NavHeader.tsx
  components/nav/NavMobileHeader.tsx
  components/nav/NavMobileSheet.tsx
  components/nav/NavSection.tsx
  lib/animations/variants.ts
  lib/hooks/useWindowResize.ts
  lib/utils/debounce.ts
Labels: :wrench: refactor, :sparkles: feat

#348 [ 폰트 ] 가져오는 방식 변경 + 랜딩 페이지 수정
  app/fonts/PretendardVariable.woff2
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/landingPage/SectionContainer.tsx
Labels: :wrench: refactor

#351 [ sheet & modal ] 뒷 배경 스크롤 작동 문제
  app/(nav)/todos/[todoId]/_view/AddLinkModal.tsx
  components/common/Modal.tsx
  components/common/Sheet.tsx
  components/drawer/TodoContentsDrawer/ActionButtons.tsx
  components/drawer/TodoContentsDrawer/TodoContentsDrawer.tsx
  components/landingPage/SectionContainer.tsx
  components/modal/ConfirmationModal.tsx
  components/modal/todoModal/TodoAddModal.tsx
  components/modal/todoModal/TodoEditModal.tsx
  components/nav/NavMobileSheet.tsx
  components/sheet/NoteViewSheet.tsx
  lib/bear/scrollStore.ts
Labels: :bug: bug, :wrench: refactor, :sparkles: feat

#347 [ 테스트 ] cypress를 이용한 E2E 테스트 셋팅 및 목표 관련 E2E 테스트 코드 추가
  .gitignore
  components/nav/NavGoal.tsx
  components/nav/NavHeader.tsx
  components/nav/NavMobileHeader.tsx
  components/nav/NavMobileSheet.tsx
  cypress.config.ts
  cypress/e2e/goals/desktop.cy.ts
  cypress/e2e/goals/mobile.cy.ts
  cypress/e2e/goals/tablet.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/index.d.ts
  lib/hooks/useDeleteGoalMutation.ts
  package-lock.json
  package.json
Labels: 🧪 test

#354 [ 공통컴포넌트 ]드롭다운 외부 클릭으로 닫히도록 수정
  components/common/DropdownMenu.tsx
Labels: :bug: bug

#357 [ 대시보드, 모든 할 일 ] 리모컨 만들기 + 로그인, 회원가입 관련 수정
  app/(nav)/layout.tsx
  components/ConfettiCanvas.tsx
  components/LoginForm.tsx
  components/ScrollToTop.tsx
  components/modal/SignupSuccessModal.tsx
  public/icons/IconScrollTop.tsx
  public/images/ImageSina.svg
Labels: :wrench: refactor, :sparkles: feat

#360 [ 할 일 관련 ] 추가, 수정, 삭제 테스트 코드 작성
  components/common/InputSlid.tsx
  cypress/e2e/todos/todo.cy.ts
  cypress/fixtures/test-file.png
Labels: 🧪 test

#362 [ 공통 컴포넌트 ] todoitem 모바일 사이즈 기능
  components/common/todoItem/TodoIcon.tsx
  components/common/todoItem/TodoTitle.tsx
  components/common/todoItem/index.tsx
  components/drawer/TodoContentsDrawer/TodoContentsDrawer.tsx
Labels: :wrench: refactor

#363 [ 대시보드 ] nav에서 목표 수정시 최근 할 일에서 수정되지 않던 오류 수정
  lib/hooks/useUpdateGoalMutation.ts
Labels: :bug: bug

#364 [ 노트 ] 노트 생성 테스트
  .gitignore
  app/(nav)/todos/[todoId]/_view/NoteFormEditorButtons.tsx
  cypress/e2e/notes/desktop.cy.ts
Labels: 🧪 test

#365 README.md
  README.md
  public/file.svg
  public/kebab.svg
  public/link.svg
  public/note.svg
  public/pencil.svg
Labels: :file_folder: docs

#369 🐛 #368 fix: 노트작석페이지 링크추가버튼 안 보임 해결
  app/(nav)/todos/[todoId]/_view/AddLinkModal.tsx
Labels: :bug: bug, :art: style

#371 [ 전체 ] 긴 문자열 단어 단위 줄바꿈 추가 및 Nav, Goal 오류 수정
  app/error.tsx
  app/not-found.tsx
  components/dashboard/GoalTodo.tsx
  components/dashboard/GoalTodoCard.tsx
  components/landingPage/FirstSection.tsx
  components/landingPage/FourthSection.tsx
  components/landingPage/SecondSection.tsx
  components/landingPage/ThirdSection.tsx
  components/nav/NavGoal.tsx
  components/nav/NavMobileHeader.tsx
  components/nav/NavProfile.tsx
  middleware.ts
Labels: :bug: bug, :art: style
