Repository FESI-4-4/slid-todo, pull requests merged in 2024-12, with the labels that each got.

#374 [ 목표 ] Nav, 최근 할 일, 새 할 일 모달 목표 상태 동일하도록 수정
  lib/hooks/useAddGoalMutation.ts
  lib/hooks/useDeleteGoalMutation.ts
Labels: :bug: bug

#376 [ 피드백 ] 페이지 컨테이너 수정 및 레이아웃 쓸데없는 div제거
  app/(nav)/dashboard/layout.tsx
  app/(nav)/dashboard/page.tsx
  app/(nav)/goals/[goalId]/layout.tsx
  app/(nav)/goals/[goalId]/page.tsx
  app/(nav)/layout.tsx
  app/(nav)/notes/[goalId]/layout.tsx
  app/(nav)/notes/[goalId]/page.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormSection.tsx
  app/(nav)/todos/[todoId]/create/layout.tsx
  app/(nav)/todos/[todoId]/create/page.tsx
  app/(nav)/todos/[todoId]/note/[noteId]/page.tsx
  app/(nav)/todos/layout.tsx
  app/(nav)/todos/page.tsx
  app/login/layout.tsx
  app/signup/layout.tsx
  components/common/pageLayout/PageContainer.tsx
  components/nav/NavMobileHeader.tsx
Labels: :wrench: refactor

#378 [ layout ] layout 수정
  app/(nav)/layout.tsx
  app/(nav)/todos/[todoId]/_view/NoteFormSections.tsx
  components/common/pageLayout/PageContainer.tsx
Labels: :art: style
